name: Random DM to AI Tweet

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  random-tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Randomize execution
        id: randomize
        run: |
          # 25% chance to proceed
          if [ $((RANDOM % 4)) -eq 0 ]; then
            echo "run_job=true" >> $GITHUB_OUTPUT
          else
            echo "run_job=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Node.js
        if: steps.randomize.outputs.run_job == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        if: steps.randomize.outputs.run_job == 'true'
        run: npm install

      - name: Run script
        if: steps.randomize.outputs.run_job == 'true'
        env:
          auth_token: ${{ secrets.auth_token }}
          ct0: ${{ secrets.ct0 }}
          twid: ${{ secrets.twid }}
        run: node index.js 